service: ${file(./config/service_name.yml):service}-${opt:stage, 'dev'}
provider:
  name: azure
  location: ${opt:location, 'West US'}
  environment:
    PROVIDER: 'azure'
plugins: 
  - serverless-azure-functions

functions:
  hello:
    handler: handler.hello
    events:
      - http: true,
        x-azure-settings:
          authLevel : anonymous 
      - http: true,
        x-azure-settings:
          direction: out
          name: res 
              
package:
  exclude: 
    - 'test/**'
    - 'coverage/**'
    - 'LICENSE'
    - 'README.md'
    - '.travis.yml'
    - 'docs/**'
    - 'config/**'
    - '.gitignore'
    - '.git/**'
    - 'package.json'