service: ${file(./config/service_name.yml):service}
provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, 'dev'}
  environment:
    STAGE: ${self:provider.stage}
    SLS_DEBUG: "*"
    PROVIDER: 'aws'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: "*"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem         
        - dynamodb:BatchGetItem 
      Resource: "arn:aws:dynamodb:*:${file(./credentials.json):environments.${self:provider.stage}.provider.aws.account}:table/*"
functions:
  readRecord:
    handler: handler.readRecord
  updateUniqueRecord:
    handler: handler.updateUniqueRecord  
  updateDataRecord:
    handler: handler.updateDataRecord
  fetchRecords:
    handler: handler.fetchRecords
  disableUniqueRecord:
    handler: handler.disableUniqueRecord
  deleteUniqueRecord:
    handler: handler.deleteUniqueRecord   
  deleteRecord:
    handler: handler.deleteRecord

package:
  exclude: 
    - 'test/**'
    - 'coverage/**'
    - 'LICENSE'
    - 'README.md'
    - '.travis.yml'
    - 'docs/**'
    - 'handler_azure.js'
